# .rubocop.yml
---
inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - govuk_design_system_formbuilder.gemspec
Rails/Date:
  Enabled: false
Rails/ActiveSupportAliases:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/FormatString:
  EnforcedStyle: format
